steps:
  - id: Build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - '$_IMAGE_NAME:$REF_NAME'
      - .
      - '-f'
      - $_DOCKERFILE_NAME
    dir: $_DOCKERFILE_DIR
  - id: Push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_IMAGE_NAME:$REF_NAME'
  - id: Prepare deploy
    name: gcr.io/cloud-builders/gke-deploy
    args:
      - prepare
      - '--filename=$_K8S_YAML_PATH'
      - '--image=$_IMAGE_NAME:$REF_NAME'
      - '--app=$_K8S_APP_NAME'
      - '--version=$REF_NAME'
      - '--namespace=$_K8S_NAMESPACE'
      - '--label=$_K8S_LABELS'
      - '--annotation=$_K8S_ANNOTATIONS,gcb-build-id=$BUILD_ID'
      - '--output=output'
  - id: Save configs
    name: gcr.io/cloud-builders/gsutil
    args:
      - '-c'
      - |-
        if [ "$_OUTPUT_BUCKET_PATH" != "" ]
        then
          gsutil cp -r output/suggested gs://$_OUTPUT_BUCKET_PATH/config/$_K8S_APP_NAME/$BUILD_ID/suggested
          gsutil cp -r output/expanded gs://$_OUTPUT_BUCKET_PATH/config/$_K8S_APP_NAME/$BUILD_ID/expanded
        fi
    entrypoint: sh
  - id: Apply deploy
    name: gcr.io/cloud-builders/gke-deploy
    args:
      - apply
      - '--filename=output/expanded'
      - '--cluster=$_GKE_CLUSTER'
      - '--location=$_GKE_LOCATION'
      - '--namespace=$_K8S_NAMESPACE'
images:
  - '$_IMAGE_NAME:$REF_NAME'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _K8S_APP_NAME: events-mq
  _DOCKERFILE_NAME: Dockerfile
  _DOCKERFILE_DIR: ''
  _GKE_CLUSTER: production-cluster
  _OUTPUT_BUCKET_PATH: avacuscc-598ae-cloudbuilds/deploy
  _K8S_YAML_PATH: .kube/staging/deployment.yaml
  _K8S_NAMESPACE: staging
  _K8S_ANNOTATIONS: ''
  _GKE_LOCATION: asia-northeast1-a
  _K8S_LABELS: ''
  _IMAGE_NAME: gcr.io/avacuscc-598ae/github.com/wakumo/events-mq
tags:
  - gcp-cloudbuild-deploy
  - $_K8S_APP_NAME