apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: staging
  name: events-mq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-mq
      version: v1
  template:
    metadata:
      labels:
        app: events-mq
        version: v1
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: pool-2
      containers:
      - name: events-mq
        image: gcr.io/avacuscc-598ae/github.com/wakumo/events-mq
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 3000
        startupProbe:
          httpGet:
            path: /healthz
            port: http
            httpHeaders:
            - name: Origin
              value: http://localhost:3000
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
            httpHeaders:
            - name: Origin
              value: http://localhost:3000
          initialDelaySeconds: 60
          periodSeconds: 10
        envFrom:
          - configMapRef:
              name: events-mq-config
          - secretRef:
              name: events-mq-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: staging
  name: events-mq-scan-events-bsc-job
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-mq-scan-events-bsc-job
      version: v1
  template:
    metadata:
      labels:
        app: events-mq-scan-events-bsc-job
        version: v1
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: pool-2
      containers:
      - name: scan-events-bsc-runtime
        image: gcr.io/avacuscc-598ae/github.com/wakumo/events-mq
        imagePullPolicy: Always
        command:
          - yarn
          - execute
          - job:scan_events
          - -c
          - '56'
        envFrom:
          - configMapRef:
              name: events-mq-config
          - secretRef:
              name: events-mq-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: staging
  name: events-mq-scan-events-polygon-job
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-mq-scan-events-polygon-job
      version: v1
  template:
    metadata:
      labels:
        app: events-mq-scan-events-polygon-job
        version: v1
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: pool-2
      containers:
      - name: scan-events-polygon-runtime
        image: gcr.io/avacuscc-598ae/github.com/wakumo/events-mq
        imagePullPolicy: Always
        command:
          - yarn
          - execute
          - job:scan_events
          - -c
          - '137'
        envFrom:
          - configMapRef:
              name: events-mq-config
          - secretRef:
              name: events-mq-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: staging
  name: events-mq-scan-events-ethereum-job
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-mq-scan-events-ethereum-job
      version: v1
  template:
    metadata:
      labels:
        app: events-mq-scan-events-ethereum-job
        version: v1
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: pool-2
      containers:
      - name: scan-events-ethereum-runtime
        image: gcr.io/avacuscc-598ae/github.com/wakumo/events-mq
        imagePullPolicy: Always
        command:
          - yarn
          - execute
          - job:scan_events
          - -c
          - '1'
        envFrom:
          - configMapRef:
              name: events-mq-config
          - secretRef:
              name: events-mq-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: staging
  name: events-mq-send-events-job
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-mq-send-events-job
      version: v1
  template:
    metadata:
      labels:
        app: events-mq-send-events-job
        version: v1
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: pool-2
      containers:
      - name: send-events-runtime
        image: gcr.io/avacuscc-598ae/github.com/wakumo/events-mq
        imagePullPolicy: Always
        command:
          - yarn
          - execute
          - job:send_events
        envFrom:
          - configMapRef:
              name: events-mq-config
          - secretRef:
              name: events-mq-secret