name: NestJS Service CI

on:
  push:
    branches: [release, develop]
  pull_request:
    branches: [release, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.14.2]

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: runner
          POSTGRES_DB: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: runner
      DB_NAME: avacuscc-events
      DB_NAME_TEST: avacuscc-events-test

      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379

      RABBITMQ_HOST: 127.0.0.1
      RABBITMQ_PORT: 5672
      RABBITMQ_EXCHANGE_NAME: avacuscc-event-mq

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn build
      - run: yarn db:create:test
      - run: yarn test
  ### Add sonarjob
  SonarqubeScan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: yarn build || true

      - name: Run tests and collect coverage
        run: yarn test --coverage || true

      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_PROJECT_KEY: avacuscc-events-mq
        run: |
          npx sonar-scanner -X \
          -Dsonar.projectKey=avacuscc-events-mq \
          -Dsonar.sources=src \
          -Dsonar.tests=test \
          -Dsonar.host.url=http://118.69.160.39:9000 \
          -Dsonar.login=${{ env.SONAR_TOKEN }} \
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
          -Dsonar.sourceEncoding=UTF-8

      - name: Upload Coverage Report
        if: success() && steps.test.outcome == 'success'
        run: npm run test:coverage